# Generated by Django 3.0.8 on 2020-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.TextField(max_length=100)),
                ('heroname', models.TextField(max_length=50)),
                ('heroinname', models.TextField(max_length=50)),
                ('director', models.TextField(max_length=50)),
                ('reldate', models.DateField(null=True)),
            ],
        ),
    ]
