# Generated by Django 3.0.8 on 2020-10-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
