# Generated by Django 3.0.8 on 2020-10-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
