# Generated by Django 3.0.8 on 2020-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20201015_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=100)),
                ('pwd', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
